k8s-service:
  containerImage:
    repository: aukilabs/domain-viewer
    tag: latest
    pullPolicy: Always
  applicationName: domain-viewer
  containerPorts:
    http:
      port: 3000
      protocol: TCP
  shutdownDelay: 5
  replicaCount: 1
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/group.name: default
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    path: "/"
    pathType: "Prefix"
    servicePort: "app"
  containerResources:
    limits:
      memory: 96Mi
    requests:
      memory: 96Mi
  envVars:
    AUKI_API_SERVER: http://api
    AUKI_DDS_SERVER: http://dds
  secrets:
    domain-viewer:
      as: envFrom
